apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.argoProject.destNamespace }}
    name: in-cluster
  project: {{ .Values.argoProject.name }}
  source:
    path: apps
    repoURL: {{ .Values.src.repoUrl }}
    targetRevision: HEAD