apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.containerPort }}