apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  
spec:
  selector:
    app: {{ .Chart.Name }}
    version: {{ .Values.image.tag }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.image.containerPort }}